// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/YuraMishin/bigtechmicroservices/order/internal/model"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// OrderRepository is an autogenerated mock type for the OrderRepository type
type OrderRepository struct {
	mock.Mock
}

type OrderRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *OrderRepository) EXPECT() *OrderRepository_Expecter {
	return &OrderRepository_Expecter{mock: &_m.Mock}
}

// CreateNewOrder provides a mock function with given fields: ctx, order
func (_m *OrderRepository) CreateNewOrder(ctx context.Context, order model.Order) {
	_m.Called(ctx, order)
}

// OrderRepository_CreateNewOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateNewOrder'
type OrderRepository_CreateNewOrder_Call struct {
	*mock.Call
}

// CreateNewOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - order model.Order
func (_e *OrderRepository_Expecter) CreateNewOrder(ctx interface{}, order interface{}) *OrderRepository_CreateNewOrder_Call {
	return &OrderRepository_CreateNewOrder_Call{Call: _e.mock.On("CreateNewOrder", ctx, order)}
}

func (_c *OrderRepository_CreateNewOrder_Call) Run(run func(ctx context.Context, order model.Order)) *OrderRepository_CreateNewOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.Order))
	})
	return _c
}

func (_c *OrderRepository_CreateNewOrder_Call) Return() *OrderRepository_CreateNewOrder_Call {
	_c.Call.Return()
	return _c
}

func (_c *OrderRepository_CreateNewOrder_Call) RunAndReturn(run func(context.Context, model.Order)) *OrderRepository_CreateNewOrder_Call {
	_c.Run(run)
	return _c
}

// GetOrderByUUID provides a mock function with given fields: ctx, orderUUID
func (_m *OrderRepository) GetOrderByUUID(ctx context.Context, orderUUID uuid.UUID) (model.Order, error) {
	ret := _m.Called(ctx, orderUUID)

	if len(ret) == 0 {
		panic("no return value specified for GetOrderByUUID")
	}

	var r0 model.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (model.Order, error)); ok {
		return rf(ctx, orderUUID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) model.Order); ok {
		r0 = rf(ctx, orderUUID)
	} else {
		r0 = ret.Get(0).(model.Order)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, orderUUID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrderRepository_GetOrderByUUID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrderByUUID'
type OrderRepository_GetOrderByUUID_Call struct {
	*mock.Call
}

// GetOrderByUUID is a helper method to define mock.On call
//   - ctx context.Context
//   - orderUUID uuid.UUID
func (_e *OrderRepository_Expecter) GetOrderByUUID(ctx interface{}, orderUUID interface{}) *OrderRepository_GetOrderByUUID_Call {
	return &OrderRepository_GetOrderByUUID_Call{Call: _e.mock.On("GetOrderByUUID", ctx, orderUUID)}
}

func (_c *OrderRepository_GetOrderByUUID_Call) Run(run func(ctx context.Context, orderUUID uuid.UUID)) *OrderRepository_GetOrderByUUID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *OrderRepository_GetOrderByUUID_Call) Return(_a0 model.Order, _a1 error) *OrderRepository_GetOrderByUUID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrderRepository_GetOrderByUUID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (model.Order, error)) *OrderRepository_GetOrderByUUID_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateOrder provides a mock function with given fields: ctx, order
func (_m *OrderRepository) UpdateOrder(ctx context.Context, order model.Order) {
	_m.Called(ctx, order)
}

// OrderRepository_UpdateOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateOrder'
type OrderRepository_UpdateOrder_Call struct {
	*mock.Call
}

// UpdateOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - order model.Order
func (_e *OrderRepository_Expecter) UpdateOrder(ctx interface{}, order interface{}) *OrderRepository_UpdateOrder_Call {
	return &OrderRepository_UpdateOrder_Call{Call: _e.mock.On("UpdateOrder", ctx, order)}
}

func (_c *OrderRepository_UpdateOrder_Call) Run(run func(ctx context.Context, order model.Order)) *OrderRepository_UpdateOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.Order))
	})
	return _c
}

func (_c *OrderRepository_UpdateOrder_Call) Return() *OrderRepository_UpdateOrder_Call {
	_c.Call.Return()
	return _c
}

func (_c *OrderRepository_UpdateOrder_Call) RunAndReturn(run func(context.Context, model.Order)) *OrderRepository_UpdateOrder_Call {
	_c.Run(run)
	return _c
}

// NewOrderRepository creates a new instance of OrderRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderRepository {
	mock := &OrderRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
