// Code generated by ogen, DO NOT EDIT.

package order_v1

// OperationName is the ogen operation name
type OperationName = string

const (
	CancelOrderByUUIDOperation OperationName = "CancelOrderByUUID"
	CreateNewOrderOperation    OperationName = "CreateNewOrder"
	GetOrderByUUIDOperation    OperationName = "GetOrderByUUID"
	PayOrderOperation          OperationName = "PayOrder"
)
