// Code generated by ogen, DO NOT EDIT.
package order_v1

type CancelOrderByUUIDRes interface {
	cancelOrderByUUIDRes()
}

type CreateNewOrderRes interface {
	createNewOrderRes()
}

type GetOrderByUUIDRes interface {
	getOrderByUUIDRes()
}

type PayOrderRes interface {
	payOrderRes()
}
