// Code generated by ogen, DO NOT EDIT.

package order_v1

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// CancelOrderByUUID implements CancelOrderByUUID operation.
	//
	// Отменить заказ по UUID.
	//
	// POST /api/v1/orders/{order_uuid}/cancel
	CancelOrder(ctx context.Context, params CancelOrderByUUIDParams) (CancelOrderByUUIDRes, error)
	// CreateNewOrder implements CreateNewOrder operation.
	//
	// Создаёт новый заказ на основе выбранных
	// пользователем деталей.
	//
	// POST /api/v1/orders
	CreateNewOrder(ctx context.Context, req *CreateOrderRequest) (CreateNewOrderRes, error)
	// GetOrderByUUID implements GetOrderByUUID operation.
	//
	// Получить заказ по UUID.
	//
	// GET /api/v1/orders/{order_uuid}
	GetOrderByUUID(ctx context.Context, params GetOrderByUUIDParams) (GetOrderByUUIDRes, error)
	// PayOrder implements PayOrder operation.
	//
	// Проводит оплату ранее созданного заказа.
	//
	// POST /api/v1/orders/{order_uuid}/pay
	PayOrder(ctx context.Context, req *PayOrderRequest, params PayOrderParams) (PayOrderRes, error)
	// NewError creates *GenericErrorStatusCode from error returned by handler.
	//
	// Used for common default response.
	NewError(ctx context.Context, err error) *GenericErrorStatusCode
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
