// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/YuraMishin/bigtechmicroservices/order/internal/model"
	mock "github.com/stretchr/testify/mock"

	order_v1 "github.com/YuraMishin/bigtechmicroservices/shared/pkg/openapi/order/v1"

	uuid "github.com/google/uuid"
)

// OrderService is an autogenerated mock type for the OrderService type
type OrderService struct {
	mock.Mock
}

type OrderService_Expecter struct {
	mock *mock.Mock
}

func (_m *OrderService) EXPECT() *OrderService_Expecter {
	return &OrderService_Expecter{mock: &_m.Mock}
}

// CancelOrder provides a mock function with given fields: ctx, orderUUID
func (_m *OrderService) CancelOrder(ctx context.Context, orderUUID uuid.UUID) (order_v1.CancelOrderRes, error) {
	ret := _m.Called(ctx, orderUUID)

	if len(ret) == 0 {
		panic("no return value specified for CancelOrder")
	}

	var r0 order_v1.CancelOrderRes
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (order_v1.CancelOrderRes, error)); ok {
		return rf(ctx, orderUUID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) order_v1.CancelOrderRes); ok {
		r0 = rf(ctx, orderUUID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(order_v1.CancelOrderRes)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, orderUUID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrderService_CancelOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelOrder'
type OrderService_CancelOrder_Call struct {
	*mock.Call
}

// CancelOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - orderUUID uuid.UUID
func (_e *OrderService_Expecter) CancelOrder(ctx interface{}, orderUUID interface{}) *OrderService_CancelOrder_Call {
	return &OrderService_CancelOrder_Call{Call: _e.mock.On("CancelOrder", ctx, orderUUID)}
}

func (_c *OrderService_CancelOrder_Call) Run(run func(ctx context.Context, orderUUID uuid.UUID)) *OrderService_CancelOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *OrderService_CancelOrder_Call) Return(_a0 order_v1.CancelOrderRes, _a1 error) *OrderService_CancelOrder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrderService_CancelOrder_Call) RunAndReturn(run func(context.Context, uuid.UUID) (order_v1.CancelOrderRes, error)) *OrderService_CancelOrder_Call {
	_c.Call.Return(run)
	return _c
}

// CreateOrder provides a mock function with given fields: ctx, req
func (_m *OrderService) CreateOrder(ctx context.Context, req *order_v1.CreateOrderRequest) (order_v1.CreateOrderRes, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrder")
	}

	var r0 order_v1.CreateOrderRes
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *order_v1.CreateOrderRequest) (order_v1.CreateOrderRes, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *order_v1.CreateOrderRequest) order_v1.CreateOrderRes); ok {
		r0 = rf(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(order_v1.CreateOrderRes)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *order_v1.CreateOrderRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrderService_CreateOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrder'
type OrderService_CreateOrder_Call struct {
	*mock.Call
}

// CreateOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - req *order_v1.CreateOrderRequest
func (_e *OrderService_Expecter) CreateOrder(ctx interface{}, req interface{}) *OrderService_CreateOrder_Call {
	return &OrderService_CreateOrder_Call{Call: _e.mock.On("CreateOrder", ctx, req)}
}

func (_c *OrderService_CreateOrder_Call) Run(run func(ctx context.Context, req *order_v1.CreateOrderRequest)) *OrderService_CreateOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*order_v1.CreateOrderRequest))
	})
	return _c
}

func (_c *OrderService_CreateOrder_Call) Return(_a0 order_v1.CreateOrderRes, _a1 error) *OrderService_CreateOrder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrderService_CreateOrder_Call) RunAndReturn(run func(context.Context, *order_v1.CreateOrderRequest) (order_v1.CreateOrderRes, error)) *OrderService_CreateOrder_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrder provides a mock function with given fields: ctx, orderUUID
func (_m *OrderService) GetOrder(ctx context.Context, orderUUID uuid.UUID) (model.Order, error) {
	ret := _m.Called(ctx, orderUUID)

	if len(ret) == 0 {
		panic("no return value specified for GetOrder")
	}

	var r0 model.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (model.Order, error)); ok {
		return rf(ctx, orderUUID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) model.Order); ok {
		r0 = rf(ctx, orderUUID)
	} else {
		r0 = ret.Get(0).(model.Order)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, orderUUID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrderService_GetOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrder'
type OrderService_GetOrder_Call struct {
	*mock.Call
}

// GetOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - orderUUID uuid.UUID
func (_e *OrderService_Expecter) GetOrder(ctx interface{}, orderUUID interface{}) *OrderService_GetOrder_Call {
	return &OrderService_GetOrder_Call{Call: _e.mock.On("GetOrder", ctx, orderUUID)}
}

func (_c *OrderService_GetOrder_Call) Run(run func(ctx context.Context, orderUUID uuid.UUID)) *OrderService_GetOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *OrderService_GetOrder_Call) Return(_a0 model.Order, _a1 error) *OrderService_GetOrder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrderService_GetOrder_Call) RunAndReturn(run func(context.Context, uuid.UUID) (model.Order, error)) *OrderService_GetOrder_Call {
	_c.Call.Return(run)
	return _c
}

// PayOrder provides a mock function with given fields: ctx, orderUUID, req
func (_m *OrderService) PayOrder(ctx context.Context, orderUUID uuid.UUID, req *order_v1.PayOrderRequest) (order_v1.PayOrderRes, error) {
	ret := _m.Called(ctx, orderUUID, req)

	if len(ret) == 0 {
		panic("no return value specified for PayOrder")
	}

	var r0 order_v1.PayOrderRes
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *order_v1.PayOrderRequest) (order_v1.PayOrderRes, error)); ok {
		return rf(ctx, orderUUID, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *order_v1.PayOrderRequest) order_v1.PayOrderRes); ok {
		r0 = rf(ctx, orderUUID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(order_v1.PayOrderRes)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, *order_v1.PayOrderRequest) error); ok {
		r1 = rf(ctx, orderUUID, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrderService_PayOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PayOrder'
type OrderService_PayOrder_Call struct {
	*mock.Call
}

// PayOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - orderUUID uuid.UUID
//   - req *order_v1.PayOrderRequest
func (_e *OrderService_Expecter) PayOrder(ctx interface{}, orderUUID interface{}, req interface{}) *OrderService_PayOrder_Call {
	return &OrderService_PayOrder_Call{Call: _e.mock.On("PayOrder", ctx, orderUUID, req)}
}

func (_c *OrderService_PayOrder_Call) Run(run func(ctx context.Context, orderUUID uuid.UUID, req *order_v1.PayOrderRequest)) *OrderService_PayOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(*order_v1.PayOrderRequest))
	})
	return _c
}

func (_c *OrderService_PayOrder_Call) Return(_a0 order_v1.PayOrderRes, _a1 error) *OrderService_PayOrder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrderService_PayOrder_Call) RunAndReturn(run func(context.Context, uuid.UUID, *order_v1.PayOrderRequest) (order_v1.PayOrderRes, error)) *OrderService_PayOrder_Call {
	_c.Call.Return(run)
	return _c
}

// NewOrderService creates a new instance of OrderService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderService(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderService {
	mock := &OrderService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
